name: Validate XML

on:
  push:
    paths:
      - '**.xml'
  pull_request:
    paths:
      - '**.xml'

permissions:
  contents: read

jobs:
  validate-xml:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync

    - name: Validate XML using Relax NG
      run: uv run python processing/validate.py
